all:
	dconf load /org/cinnamon/ < cinnamon.dconf
	dconf load /org/cinnamon/desktop/keybindings/ < cinnamon-keybindings.dconf
	dconf load /org/nemo/ < nemo.dconf
	dconf load /org/gnome/terminal/ < gnome-terminal.dconf
