#! /bin/sh

export WINEPREFIX=$HOME/.wine32
export XDG_CURRENT_DESKTOP='bspwm:X-Cinnamon:XFCE'
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.metacitythemename=Mint-Y-Dark-Custom"
dunst &
sxhkd 2>&1 | egrep -v 'nemo.*connect\(\) failed' | grep -v '\(audio_device_pulse_linux\|device_info_linux\).cc' &
tint2 2>&1 | grep -v '^tint2: Executing:' &
xsettingsd &
compton --invert-color-include '_COMPTON_INVERT:8c > 0' &
if which xfce4-screensaver; then \
	xfce4-screensaver &
else
	xscreensaver -no-splash &
	xscreensaver-dunst-fix.sh &
fi
bspwm-ignore-new-windows.sh &
bspwm-sfml-fix.sh &
bspwm-new-floating-above.sh &
bspwm-unminimize-event.sh &
bspwm-tint2-compton-transparecy.sh 80 &
bspwm-focused-child-bigger.sh daemon &
xfce4-power-manager &
lxpolkit &
nm-applet 2>&1 | grep -v 'widget' &
feh --bg-scale /usr/share/backgrounds/linuxmint/bookwood_linuxmint.jpg
setxkbmap -layout us,ru
xkbcomp $HOME/.config/xkb/my $DISPLAY
numlockx on
xsetroot -cursor_name left_ptr

run_desktop=$(which exo-open || echo pcmanfm)
for i in ~/.config/autostart/*.desktop
do
	$run_desktop $i
done

# Fix swing applications
which wmname >> /dev/null && wmname LG3D

bspc monitor -d "ctl(1)" "web(2)" "msg(3)" "mus(4)" "cal(5)" "gp1(6)" "gp2(7)" "gp3(8)" "gp4(9)" "emu(0)"

bspc config border_width         2
bspc config window_gap          12

bspc config normal_border_color   \#424242
bspc config focused_border_color  \#42BD00
bspc config presel_feedback_color \#bdbd42

bspc config split_ratio          0.6176
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config initial_polarity     first_child
bspc config automatic_scheme     spiral

bspc config pointer_modifier     mod4
bspc config pointer_action1      resize_side
bspc config pointer_action2      move
bspc config pointer_action3      resize_corner
bspc config click_to_focus       button1
bspc config swallow_first_click  true
bspc config ignore_ewmh_focus    true
bspc config external_rules_command "$(dirname "$(realpath -s "$(which "$0")")")"/scripts/external_rules_command

bspc rule -a Gnome-calculator state=floating
bspc rule -a Onboard state=floating
bspc rule -a libreoffice state=tiled
bspc rule -a Soffice state=tiled
# For the floating window during video calls:
bspc rule -a Skype state=floating
bspc rule -a Skype -o state=tiled
bspc rule -a Firefox:Picture-in-Picture state=floating
bspc rule -a xmessage state=floating center=on
bspc rule -a "Acme SAC" -o state=pseudo_tiled
bspc rule -a "Zathura" state=tiled
bspc rule -a "Emacs" state=tiled

(while true; do [ "$(xkb-switch -l | wc -l)" -eq 1 ] && (setxkbmap -layout us,ru; xkbcomp $HOME/.config/xkb/my $DISPLAY); sleep 5; done) &
