#! /bin/sh

if [ "$2" = TelegramDesktop ]; then \
	exec "$0-telegram" "$@"
fi

if [ "$2" = zoom ]; then \
	exec "$0-zoom" "$@"
fi

if [ "$2" = Firefox ]; then \
	exec "$0-firefox" "$@"
fi

if [ "$2" = mpv ]; then \
	exec "$0-mpv" "$@"
fi
